### PR TITLE
More robust memory mapping, CI and C/CXX FFI

### PR DESCRIPTION
**Pull request by eternal-flame-AD**
This PR is mainly robustness and quality of life improvements. I plan to use this as a stable base so I can look at algorithmic improvements without worrying about breaking something.

# Refactoring

Refactored some reusable parts from `main.rs` into `lib.rs` so they can be used by library users & integration tests.

# Integration Tests

Currently the code did not test if the actual sorted data are correct, I wrote an integration test to make sure that both mmaped and sequential processing yield the same data that is further compared with an expected value.

# Memory Mapping Corrections

I got my hands on a MacOS system and fixed the mapping code. The main difference is transparent huge pages are not supported. I didn't find a credible source on how to make huge page happen on MacOS and remote debugging on GitHub Actions or my friend is just not worth the investment, but at least now with Integration Tests I can be sure mmap works without huge pages.

The same problem exists on some Windows systems too (like Github Actions) so I removed them too for compatibility.

# C/CXX FFI

People may want to write bindings to your library, Rust is unfortunately still not popular enough in Bioinformatics. If we have a C/C++ API it would be much easier for them to integrate. I wrote a test too but I didn't include it in the CI because I feel changes to the API wrappers are infrequent enough that doesn't justify the large time investment in making the CI work across all platforms. The integration test is based on CMake with C++. The following should do it:

```sh
cd ci/c_ffi
mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Release "-GUnix Makefiles" ..
make check
```

For usage see the [test file](https://github.com/eternal-flame-AD/faster-gtfsort/blob/master/ci/c_ffi/test_ffi.cxx). It's quite simple most lines are for assertions and testing.

Header files for full API: [C](https://github.com/eternal-flame-AD/faster-gtfsort/blob/master/include/gtfsort.h) [C++](https://github.com/eternal-flame-AD/faster-gtfsort/blob/master/include/gtfsort.hxx)

# CI

I wrote GitHub actions workflow file which does the following on each of `[macos, windows, linux] * [nightly, stable]` So later we don't need to get 3 different systems to make sure we didn't break anything:

- Checks the code lints and compiles with a minimal set of features and with a complete set of features
- Checks the C and C++ header files are up to date (linux only).
- Runs the unit tests and integration tests.
- Uploads the header files, `gtfsort` binary and shared object as artifact. I tested on linux the only dependency is libc and I can just download it from GitHub actions and run the binary or link the shared object. This means automated multi-platform binary release on tag is possible!

Then if the commit message includes `[ci benchmark]`, a benchmark is ran on each of the three platforms, compared to `origin/master`. Results are automatically submitted as a commit comment. Currently benchmark on windows and macos doesn't work because the current branch HEAD has compatibility problems with GitHub actions. After this is merged this should get resolved. Here's a sample comment: https://github.com/eternal-flame-AD/faster-gtfsort/commit/57651c378bfebe245fc60d218f40d4fe75dc16d4#commitcomment-145005867

here is a sample [job log](https://github.com/eternal-flame-AD/faster-gtfsort/actions/runs/10230893093)

### CODE REVIEW

**Comment by alejandrogzi** [comment]
@eternal-flame-AD 

Amazing work and big thanks for your time! 

> People may want to write bindings to your library, Rust is unfortunately still not popular enough in Bioinformatics. If we have a C/C++ API it would be much easier for them to integrate. I wrote a test too but I didn't include it in the CI because I feel changes to the API wrappers are infrequent enough that doesn't justify the large time investment in making the CI work across all platforms.

I haven't had the opportunity to do C externals, but thanks for this additional feature. Now that the algorithm core is exposed as lib, make sense to also port that to python (will push that after merging this PR). 

Let me know if you have any additional ideas/projects!

**Comment by eternal-flame-AD** [comment]
Thanks for the merge! I will look at the algorithm probably later next week to see if I can improve. I think the timing is good enough for most researches but memory wise I would like to try if I can do more.

As with the FFI I am more familiar with R than Python. I might write an R library for this. It will be a separate repo because R packages need to be in their own repository.

**Comment by eternal-flame-AD** [comment]
I am working on my own project on GFF too (partly why I found your project is because I think it would be good to have this as a preprocessor for my project), it's called GFidx which produces a compact GFF index file for fast lookups over the file system or the network. I will publish it when it's polished enough .

Here's a presentation with some preliminary results if you are interested: https://blob.yumechi.jp/pub/20246_BIOL5382/presentation.html

**Comment by alejandrogzi** [comment]
> Thanks for the merge! I will look at the algorithm probably later next week to see if I can improve. I think the timing is good enough for most researches but memory wise I would like to try if I can do more.

That will be amazing! 

> As with the FFI I am more familiar with R than Python. I might write an R library for this. It will be a separate repo because R packages need to be in their own repository.

I just pushed the py port, nothing fancy, though. With respect to the R port, I have not had the opportunity to extern rust-to-R; however I have seen that this is possible from a single repo by installing remotely from gh (check this example: [r-oxbow](https://github.com/abdenlab/oxbow/tree/main/r-oxbow)). Would be nice to have all ports in 1 repo but feel free to continue with your desire approach, just let me know if I can help or share the repo link.

> I am working on my own project on GFF too (partly why I found your project is because I think it would be good to have this as a preprocessor for my project), it's called GFidx which produces a compact GFF index file for fast lookups over the file system or the network. I will publish it when it's polished enough .

Your project looks pretty cool! Glad to have contributed (in some indirect way). I also created a pack of converters bed-to-tgf/gff and viceversa, all in rust. I think that they can definitely be enhanced with your algorithm. Right now they work with a pretty similar approach (not as cool and efficient as yours): 1) build a tree-like structure based on chr -> gene -> attributes and 2) perform coordinate calculations on each leaf in parallel. 

At the pure bioinfo level I am "trying" to work on a rust library for chain files: [chaintools](https://github.com/alejandrogzi/chaintools). That version is really outdated and have changed a lot. I am trying to perform operations on genome alignments and pack everything using arrow to serialize huge files in the most efficient way possible (and also pyarrow to port everything 0-copy to python) and still have not come with a more clever algorithm to liftover things or play with alignment gaps and other stuff.  Feel free to reach out if you are interested or have some ideas! 

I will be updating the README and paper (which are the only thing missing right now) in the following days.

Again, thanks for your time and pretty cool ideas, really looking forward to contribute to your project! 

Alejandro

**Comment by eternal-flame-AD** [comment]
> Would be nice to have all ports in 1 repo but feel free to continue with your desire approach, just let me know if I can help or share the repo link.

Will look at that probably tomorrow, if you are planning on bumping to 1.0.0 could you hold on to it for now?

> At the pure bioinfo level I am "trying" to work on a rust library for chain files: [chaintools](https://github.com/alejandrogzi/chaintools).

I will look at it! Probably won't have time to write the friendly and Python API but will look at how to pack, serialize, de-serialize and unpack it as efficiently as possible!

> I will be updating the README and paper (which are the only thing missing right now) in the following days.

Thanks!

**Pull request merged**
